/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子，JAR，小蓝，好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    ") experience\n                            and": ") 经验\n 和",
    "A quarter of a thousand": "千分之四",
    "Build a sword trap": "建造一个剑阵陷阱",
    "Enemy": "敌人",
    "experience\n                            and": "经验\n和",
    "Get your slimes to level 1": "让你的史莱姆达到 1 级",
    "Kill 250 innocent slimes": "杀死 250 个无辜的史莱姆",
    "Kill an innocent slime": "杀死 1 只无辜的史莱姆",
    "kills": "击杀",
    "Murderer": "凶手",
    "Passive damage": "被动伤害",
    "Reapply": "重新申请",
    "Reapply your first 3 upgrades' effects": "重新应用前 3 次升级的效果",
    "Short tooltip mode": "短工具提示模式",
    "Tougher enemies": "更强硬的敌人",
    "Try refreshing the page if this is your first time": "如果这是您第一次尝试刷新页面",
    "Upgrades": "升级",
    "XP": "经验",
    "Achievement Unlocked!": "成就已解锁！",
    "Bloodthirst": "渴血",
    "Double damage": "双倍伤害",
    "Enemy kills boost experience gain": "击杀敌人可增加经验值",
    "Monsters have more health and give more experience": "怪物拥有更多生命值并提供更多经验",
    "Sharper Sword": "更锋利的剑",
    "Stronger Monsters": "更强的怪物",
    "Bloodlust": "嗜血",
    "Enemy health boosts damage": "敌人的生命值会增加伤害",
    "Sword Trap": "剑阵陷阱",
    "+1.00 times": "+1.00 次",
    "Better Power": "更好的力量",
    "Book of Numbers": "数字之书",
    "Deal 50% more damage": "造成额外 50% 伤害",
    "Double experience gain": "双倍经验获得",
    "Experience boosts damage": "经验增加伤害",
    "Notebook": "笔记本",
    "Orange  slime": "橙色史莱姆",
    "Reapply first row upgrades effects": "重新应用第一行升级效果",
    "Sword of Knowledge": "知识之剑",
    "Unlock 2 new layers": "解锁 2 个新层",
    "Book of Slimes": "史莱姆之书",
    "Brain": "脑子",
    "Bronze Ingot": "青铜锭",
    "Coal": "煤炭",
    "Copper Ingot": "铜锭",
    "Copper Ore": "铜矿",
    "Crafting": "制作",
    "Danger approaches": "危险逼近",
    "Get a level": "获得一级",
    "Gold Ingot": "金锭",
    "Gold Ore": "金矿",
    "Holy Water": "圣水",
    "Inventory": "库存",
    "Iron Ingot": "铁锭",
    "Iron Ore": "铁矿石",
    "Leaf": "树叶",
    "levels": "等级",
    "Lootbag": "战利品袋子",
    "No sources": "无来源",
    "Normal Log": "普通原木",
    "Plank": "木板",
    "Pyrite Coin": "黄铁矿币",
    "Red Fabric": "红色布料",
    "Rotten Flesh": "腐肉",
    "Rusty Gear": "生锈的装备",
    "Seed": "种子",
    "Skill points:": "技能点数：",
    "Skills": "技能",
    "Slime Core": "史莱姆核心",
    "Slime Core Shard": "史莱姆核心碎片",
    "Slime Goo": "粘液",
    "Soaked Log": "浸泡过的原木",
    "Start getting items from your kills": "开始从击杀中获取物品",
    "Steel Ingot": "钢锭",
    "Sticky Trap": "粘性陷阱",
    "Stone": "石头",
    "Stone Brick": "石砖",
    "Storage Slime": "储存史莱姆",
    "Tin Ingot": "锡锭",
    "Tin Ore": "锡矿石",
    "Unlock a skill to deal more damage": "解锁技能以造成更多伤害",
    "Yellow  slime": "黄色史莱姆",
    "Another trap": "另一个陷阱",
    "Full passive": "全被动",
    "Get an item": "获得一个物品",
    "Keep all experience upgrades": "保留所有经验升级",
    "Keep killing": "继续杀戮",
    "Keep your sword trap": "保留你的剑阵陷阱",
    "Make a book of slimes": "制作一本史莱姆之书",
    "Make a sticky trap": "制作一个粘性陷阱",
    "Slime formation": "史莱姆编队",
    "Sweet loot": "甜蜜的战利品",
    "never": "从不",
    "Add 1.00 skills points to attacking": "增加 1.00 技能点到 攻击",
    "Advanced reading techniques": "高级阅读技巧",
    "Back for blood": "回来取血",
    "Gain a level": "获得 1 等级",
    "Get 10 levels of ???": "获得 10 等级 关于 ???",
    "Get 3 levels": "获得 3 点击",
    "Learned to learn": "学会了学习",
    "Level up!": "升级！",
    "Remove 1.00 skills points from attacking": "移除 1.00 点技能点从 攻击",
    "Trained attack": "训练有素的攻击",
    "Unlock a skill to get more experience": "解锁技能以获得更多经验",
    "(hardcapped) experience\n                            and": "（硬上限）经验\n和",
    ") kills": "）击杀",
    "Blue  slime": "蓝色史莱姆",
    "Brown  slime": "棕色史莱姆",
    "Calm before the storm": "暴风雨前的平静",
    "Defeat ???": "击败 ？？？",
    "Defeat the Slime King": "击败史莱姆之王",
    "Destroy ???": "摧毁 ？？？",
    "Diligent": "勤奋",
    "Fight the first boss": "与第一个Boss战斗",
    "Get 10 levels of attacking": "获得 10 攻击等级",
    "Hungry for more": "渴望更多",
    "Stonks": "猛烈攻击",
    "A bigger can": "更大的罐头",
    "Anvil": "铁砧",
    "Autonomous": "自主性",
    "Boss challenges are automatically entered and cannot be exited.": "Boss 挑战会自动进入且无法退出。",
    "bosses": "Boss",
    "Bosses": "Boss",
    "copper ore, and": "铜矿石，以及",
    "Copper Pickaxe": "铜镐",
    "Double ore health": "双倍矿石生命值",
    "Get a copper golem": "获得一个铜傀儡",
    "Get a drill": "获得一个钻头",
    "Get a filter": "获取过滤器",
    "Get a stone furnace": "获得一个石炉",
    "Get a stone tablet": "获得一块石碑",
    "Get a tin chest": "得到一个锡箱",
    "Get enough tin chests to keep Copper Drill": "获得足够的锡箱来存放铜钻",
    "Heating up": "加热",
    "In boss challenge:": "在Boss挑战中：",
    "In challenge:": "挑战中：",
    "Keep all mining upgrades": "保留所有挖矿升级",
    "Kill another thousand slimes.": "再杀死 1000 只史莱姆。",
    "Kills boost ore chances (does not apply to stone)": "击杀会增加矿石机会（不适用于石头）",
    "Mine something": "开采一些东西",
    "Mining": "采矿",
    "More stone": "更多的石头",
    "Off to never visit again": "离开不再访问",
    "Ore health boosts mining chance": "矿石生命值提高采矿几率",
    "Permanent mark": "永久标记",
    "Reward:": "奖励：",
    "Rock and stone": "岩石和石头",
    "Slime health is multiplied by 5, unlock a new layer.": "史莱姆生命值乘以 5，解锁新层。",
    "Slime King's Wrath": "史莱姆王之怒",
    "Start crafting stone items": "开始制作石制品",
    "Stay passive": "保持被动",
    "Stone Pickaxe": "石镐",
    "stone,": "石头，",
    "The helper we never got": "我们从未得到过的帮助者",
    "The Slime King has a lot of treasure, surely you can find something of use in there.": "史莱姆王有很多宝藏，你一定能在里面找到有用的东西。",
    "tin ore.": "锡矿石.",
    "Tin Pickaxe": "锡镐",
    "Your next boss will be at 1,000 goblin kills": "你的下一个 Boss 在杀死 1,000 只哥布林时出现",
    "Copper Drill": "铜钻",
    "Automatically mine the whole ore when it's full": "矿石满时自动开采全部矿石",
    "Allow crafting items with metals": "允许用金属制作物品",
    "Ore health boosts ore regeneration speed": "矿石生命值提高矿石再生速度",
    "Stone boosts damage": "石头可以提高伤害",
    "Stone Sword": "石剑",
    "Tin Anvil": "锡砧",
    "Tin boosts max ore health": "锡可提高矿石最大生命值",
    "Tin Minecart": "锡矿车",
    "'s effect is changed": "的效果已经改变",
    "Copper Filter": "铜过滤器",
    "Get as much stone as ores": "获得与矿石一样多的石头",
    "Stop getting stone otherwise": "否则就别再拿石头了",
    "Stone boosts skill speed": "石头可以提高技能速度",
    "Stone Tablet": "石碑",
    "Copper Golem": "铜傀儡",
    "Kills boost mining chance": "击杀数增加采矿机会",
    "Stone Furnace": "石炉",
    "Tin Chest": "锡箱",
    "Requires an anvil": "需要一个铁砧",
    "'s effect is doubled.": "的效果翻倍。",
    "Blue": "蓝色",
    "Blue  goblin": "蓝色哥布林",
    "Bonus Achievements": "奖励成就",
    "Coin Bag": "零钱袋",
    "Color": "颜色",
    "Cryptoslime": "隐秘史莱姆",
    "Doubles time speed": "时间速度加倍",
    "Enemy kills boost damage": "杀死敌人会增加伤害",
    "Experience": "经验",
    "Experience boosts experience gain": "经验可增加经验增益",
    "Fix The Clock": "修理时钟",
    "Forbidden Knowledge": "禁忌知识",
    "Gear Golems": "装备傀儡",
    "Get 10 levels of learning": "获得 10 个学习等级",
    "Goblin": "哥布林",
    "Goblins can also drop slime items at 10% of the rate.": "哥布林还可以以 10% 的速度掉落粘液物品。",
    "Health": "生命值",
    "Hour Hand": "时针",
    "Kills": "击杀",
    "Mini-boss challenges are optional.": "迷你Boss挑战是可选的。",
    "Mini-boss challenges cannot be exited.": "迷你Boss挑战无法退出。",
    "Mini-Bossess": "迷你Boss",
    "Minute Hand": "分针",
    "Missing piece of The Clock": "时钟缺失的一块",
    "New XP upgrades, slime item drops are doubled.": "新的 经验 升级，史莱姆物品掉落加倍。",
    "Red": "红色",
    "Red Slime": "红色史莱姆",
    "Relic challenges are optional.": "遗物挑战是可选的。",
    "Relics": "遗物",
    "Second Hand": "二手货",
    "Slime": "史莱姆",
    "Slime Prince's Anger": "史莱姆王子的愤怒",
    "Sword of Death": "死亡之剑",
    "The Broken Clock": "坏掉的钟",
    "Time is much slower. This affects all passive content.": "时间慢了很多。 这会影响所有被动内容。",
    "Time Speed": "时间速度",
    "Unlock goblins and keep the new layer. Your experience upgrades are always visible and": "解锁哥布林并保留新层。 您的体验升级始终可见，并且",
    "Unlock The Clock, a special layer to speed time up.": "解锁时钟，一个加快时间的特殊层。",
    "You can only fight slimes, and their health is multiplied by 2.5. Most other layers are disabled.": "你只能对抗史莱姆，它们的生命值会乘以 2.5。 大多数其他层都被禁用。",
    "Magenta": "品红",
    "'s formula": "的公式",
    "+1.00 value per item": "每件物品价值 +1.00",
    "Add 1.00 skills points to learning": "学习加1.00技能点",
    "All resource gains are divided by log10(amount + 10), unlock a new layer.": "所有资源增益除以log10(数量+10)，解锁新层。",
    "Allows completion of the challenge": "允许完成挑战",
    "Allows getting items and crafting with metals.": "允许获取物品并用金属进行制作。",
    "also affects all enemies at half its amount.": "对所有敌人的影响也减半。",
    "and": "和",
    "Better Paper": "更好的纸",
    "Black": "黑色",
    "Blueprint Makers": "蓝图制作者",
    "Book of Skills": "技能之书",
    "bronze coins": "铜币",
    "bronze coins and": "铜币和",
    "Buy crafting tools": "购买制作工具",
    "Buying a loan increases the price of all the others": "购买贷款会增加所有其他贷款的价格",
    "Cash Shop": "商城",
    "Changes the effect of": "改变的效果",
    "Coins boost damage": "金币可以增加伤害",
    "copper coins": "铜币",
    "Cost:": "成本：",
    "Crafting Quality Improvements": "工艺质量改进",
    "Crafting Tools": "制作工具",
    "Defeat the goblin CEO": "击败哥布林首席执行官",
    "Get 5 levels": "获得 5 个等级",
    "Get a coin": "获得一枚硬币",
    "Get the strongest investment": "获得最强投资",
    "Get your cheaper levels": "获得更便宜的等级",
    "Gray red": "灰红色",
    "Increase effects of first column of upgrades": "增加第一列升级的效果",
    "Increase item values": "增加物品价值",
    "Keep on crafting": "继续制作",
    "Levels boost coins gain": "等级提升金币增益",
    "Loans": "贷款",
    "Loans decrease level costs": "贷款降低成本",
    "Mining chance is rooted, and it can go above 1": "挖矿机会是固定的，并且可以超过 1",
    "Mining Map": "采矿地图",
    "More Investments": "更多投资",
    "Multi-Level Marketing": "多层次营销",
    "Negate copper ore challenge penality": "取消铜矿石挑战处罚",
    "Negate experience challenge penality": "否定经验挑战惩罚",
    "Negate kills challenge penality": "否定击杀挑战处罚",
    "Negate levels challenge penality": "消极等级挑战惩罚",
    "Negate pyrite coin challenge penality": "取消黄铁矿币挑战惩罚",
    "Negate red fabric challenge penality": "取消红布挑战处罚",
    "Negate rusty gear challenge penality": "取消生锈装备挑战处罚",
    "Negate slime core shards challenge penality": "取消史莱姆核心碎片挑战惩罚",
    "Negate slime cores challenge penality": "否定史莱姆核心挑战处罚",
    "Negate slime goo challenge penality": "取消史莱姆粘挑战惩罚",
    "Negate stone challenge penality": "否定石子挑战惩罚",
    "Negate tin ore challenge penality": "取消锡矿石挑战处罚",
    "Next at 100.00 total value": "接下来的总价值为 100.00",
    "Pay off your loan.": "还清你的贷款。",
    "Real money": "真钱",
    "Remove 1.00 skills points from learning": "从学习中删除 1.00 技能点",
    "Repay Boss Loan": "偿还Boss贷款",
    "Repay Copper Ore Loan": "偿还铜矿石贷款",
    "Repay Experience Loan": "偿还体验贷款",
    "Repay Kills Loan": "还款杀死贷款",
    "Repay Levels Loan": "还款等级贷款",
    "Repay Pyrite Coin Loan": "偿还硫铁矿币贷款",
    "Repay Red Fabric Loan": "偿还红布贷款",
    "Repay Rusty Gear Loan": "偿还生锈的装备贷款",
    "Repay Slime Core Shards Loan": "偿还史莱姆核心碎片贷款",
    "Repay Slime Cores Loan": "偿还史莱姆核贷款",
    "Repay Slime Goo Loan": "偿还史莱姆咕贷款",
    "Repay Stone Loan": "偿还石头贷款",
    "Repay Tin Ore Loan": "偿还锡矿石借款",
    "Respec Loans": "重新指定贷款",
    "Scammer": "骗子",
    "Sell your items for": "出售您的物品获得 ",
    "Shiny Sword": "闪亮的剑",
    "Shop upgrades reduce loot crafting costs": "商店升级可降低战利品制作成本",
    "Skill points are stronger": "技能点数更强",
    "Start a MLM": "开始传销",
    "The Goblin CEO": "哥布林CEO",
    "Trickled Down": "涓涓细流",
    "Unlock a skill to boost some upgrades": "解锁一项技能以提升一些升级",
    "Unlock zombies and keep the new layer. Your mining upgrades are always visible and": "解锁僵尸并保留新层。 您的采矿升级始终可见，并且",
    "Your next boss will be at 1,000 zombie kills": "你的下一个boss将会在杀死 1,000个 僵尸后出现",
    "Gray orange": "灰橙",
    "Black  goblin": "黑色哥布林",
    "Amalgam": "汞合金",
    "Beat all 4 bonus bosses": "击败全部 4 个奖励 Boss",
    "Boss Star": "Boss之星",
    "Defeat the Slime Prince": "击败史莱姆王子",
    "Going global": "走向全球",
    "Gray": "灰色",
    "Gray  goblin": "灰哥布林",
    "Revenge": "复仇",
    "Second in power": "二当家",
    "Yellow": "黄色",
    "Shallow mining": "浅层采矿",
    "Zombie": "僵尸",
    "Allows deep mining": "允许深部采矿",
    "Boost": "提升",
    "Boost copper ore gain based on investments owned": "基于拥有的投资提升铜矿石收益",
    "Boost experience gain based on investments owned": "根据拥有的投资提升经验增益",
    "Boost investments amount by bosses": "增加Boss的投资金额",
    "Boost kills gain based on investments owned": "提升击杀基于所拥有投资的收益",
    "Boost pyrite coin gain based on investments owned": "根据拥有的投资提升黄铁矿币收益",
    "Boost red fabric gain based on investments owned": "根据拥有的投资提升红布收益",
    "Boost rusty gear gain based on investments owned": "根据拥有的投资提升生锈的装备增益",
    "Boost slime core gain based on investments owned": "根据拥有的投资提升史莱姆核心收益",
    "Boost slime core shard gain based on investments owned": "根据拥有的投资提高史莱姆核心碎片收益",
    "Boost slime goo gain based on investments owned": "根据拥有的投资增加粘液收益",
    "Boost stone gain based on investments owned": "根据拥有的投资增加石头收益",
    "Boost tin ore gain based on investments owned": "基于拥有的投资提高锡矿石收益",
    "Buying an investment increases the price of all the others": "购买一项投资会增加所有其他投资的价格",
    "Carbon mining": "碳开采",
    "Coal boosts tree damage": "煤炭加剧树木损坏",
    "Coal Brazier": "煤火盆",
    "Coal Forge": "煤锻炉",
    "Coal Pickaxe": "煤镐",
    "coal,": "煤炭，",
    "copper ore,": "铜矿石，",
    "Deeper down": "更深入",
    "Defeat the goblin president": "击败哥布林总统",
    "Double mining chance": "双倍挖矿机会",
    "Double price of final debt.": "最终债务的双倍价格。",
    "Doubles stone gain": "石头增益加倍",
    "DPS": "输出功率",
    "effect": "影响",
    "every": "每个",
    "Fake coins": "假币",
    "Fire Axe": "消防斧",
    "Free crafts": "免费工艺品",
    "Get a coal pickaxe": "获取煤镐",
    "Get a free pile of gold": "获得一堆免费的金子",
    "Get all 4 relics": "获得全部 4 件遗物",
    "Get all drops from an enemy at once without any chance boost": "一次获得敌人的所有掉落物，没有任何机会提升",
    "Get bonus levels to crafted items": "获得制作物品的奖励等级",
    "Get new debts to pay off.": "获得新的债务来偿还。",
    "Get some more fake coins to sell": "多买一些假币来卖",
    "Go deeper in the earth": "深入地球深处",
    "Gold boosts coin gain": "黄金提升代币收益",
    "Gold boosts drop chances": "黄金增加下跌机会",
    "Gold Coins": "金币",
    "Gold Collector": "黄金收藏家",
    "gold ore.": "金矿。",
    "Gold Pickaxe": "金镐",
    "Gold Pile": "金堆",
    "Gold pile (empty)": "金堆（空）",
    "Green": "绿色",
    "How does this thing even stay intact?": "这东西怎么能完好无损？",
    "In strides": "大步流星",
    "Increase tree damage": "增加树木伤害",
    "Increases amount of mined ores": "增加开采矿石量",
    "Invest in Bosses": "投资Boss",
    "Invest in Copper Ore": "投资铜矿石",
    "Invest in Experience": "投资经验",
    "Invest in Kills": "投资击杀",
    "Invest in Levels": "投资等级",
    "Invest in Pyrite Coins": "投资黄铁矿币",
    "Invest in Red Fabric": "投资红色布料",
    "Invest in Rusty Gears": "投资生锈的装备",
    "Invest in Slime Core Shards": "投资史莱姆核心碎片",
    "Invest in Slime Cores": "投资史莱姆核心",
    "Invest in Slime Goo": "投资粘液",
    "Invest in Stone": "投资石头",
    "Invest in Tin Ore": "投资锡矿石",
    "Investments": "投资",
    "Investments are reset on boss reset": "Boss重置时投资也会重置",
    "Investments decrease level costs": "投资降低成本",
    "Iron Axe": "铁斧",
    "Iron Battle Axe": "铁战斧",
    "Iron Chest": "铁箱",
    "iron ore, and": "铁矿石，以及",
    "Iron Pickaxe": "铁镐",
    "Iron Shaft": "铁轴",
    "Kills boost ore health": "杀戮促进矿石生命值",
    "Knowledge Ball": "知识球",
    "Lose 1% (rounded down) of your lower rows resources every second.": "每秒损失 1%（向下舍入）较低的行资源。",
    "monsters every second (see Info tab for current DPS)": "每秒怪物数量（有关当前 DPS，请参阅“信息”选项卡）",
    "Passively deal 25% of your damage to": "被动对你造成 25% 的伤害",
    "Pay off your debt": "还清你的债务",
    "Production per second depends on the layer doing it": "每秒的产量取决于执行此操作的层",
    "Pure luck": "纯属运气",
    "Reduce level cost based on investments owned": "根据拥有的投资降低等级成本",
    "Relic Star": "遗迹之星",
    "Respec Investments": "重新指定投资",
    "Roll the dice": "掷骰子",
    "Rotten Bag": "烂袋子",
    "Secret Achievements": "秘密成就",
    "The Goblin President": "哥布林总统",
    "tin ore,": "锡矿石,",
    "Unlock ???": "开锁 ？？？",
    "Unlock a new layer": "解锁一个新层",
    "Unlock the Clock": "解锁时钟",
    "Unlock the forge": "解锁熔炉",
    "Wizardry": "巫术",
    "Your portfolio grows, goblin item drops are doubled.": "你的投资组合会增加，哥布林物品掉落会翻倍。",
    "Mining shallow": "开采浅层",
    "Applies time speed to boss layer": "将时间速度应用于 Boss 层",
    "Applies time speed to experience layer": "将时间速度应用于体验层",
    "Applies time speed to level layer": "将时间速度应用于关卡层",
    "Applies time speed to loot layer": "将时间速度应用于战利品层",
    "Applies time speed to mining layer": "将时间速度应用于挖掘层",
    "Boss connector": "Boss连接器",
    "Cost: Free!": "成本：免费！",
    "Crude Bronze Gear": "粗青铜装备",
    "Experience connector": "体验连接器",
    "Goblin Gear": "妖精装备",
    "Gold Gear": "黄金装备",
    "Iron Gear": "铁装备",
    "Level connector": "液位连接器",
    "Loot connector": "战利品连接器",
    "Mining connector": "矿用连接器",
    "Money Gear": "金钱装备",
    "Shop connector": "商店连接器",
    "Slime Gear": "史莱姆装备",
    "Stone Gear": "石头装备",
    "Time Gears": "时间装备",
    "Time speed is lower for higher rows": "行数越高，时间速度越慢",
    "Zombie Gear": "僵尸装备",
    "Black  zombie": "黑色的僵尸",
    "Debts": "债务",
    "Negate brain challenge penality": "否定大脑挑战惩罚",
    "Negate coal challenge penality": "取消煤炭挑战处罚",
    "Negate gold ore challenge penality": "取消金矿石挑战处罚",
    "Negate iron ore challenge penality": "取消铁矿石挑战处罚",
    "Negate rotten flesh challenge penality": "取消腐肉挑战处罚",
    "Repay Boss Debt": "偿还老板债务",
    "Repay Brain Debt": "偿还脑债",
    "Repay Coal Debt": "偿还煤炭债务",
    "Repay Copper Ore Debt": "偿还铜矿石债务",
    "Repay Experience Debt": "偿还经验债务",
    "Repay Gold Ore Debt": "偿还金矿石债务",
    "Repay Iron Ore Debt": "偿还铁矿石债务",
    "Repay Kills Debt": "偿还击杀债务",
    "Repay Levels Debt": "偿还等级债务",
    "Repay Pyrite Coin Debt": "偿还黄铁矿币债务",
    "Repay Red Fabric Debt": "偿还红布债务",
    "Repay Rotten Flesh Debt": "偿还腐肉债务",
    "Repay Rusty Gear Debt": "偿还生锈的装备债务",
    "Repay Slime Core Shards Debt": "偿还史莱姆核心碎片债务",
    "Repay Slime Cores Debt": "偿还史莱姆核心债务",
    "Repay Slime Goo Debt": "偿还史莱姆粘液债务",
    "Repay Stone Debt": "偿还石头债务",
    "Repay Tin Ore Debt": "偿还锡矿石债务",
    "Respec Debts": "重新指定债务",
    "Applies time speed to forge layer": "将时间速度应用于锻造层",
    "Applies time speed to tree layer": "将时间速度应用于树层",
    "Better minerals": "更好的矿物质",
    "Bigger trees": "更大的树",
    "Build a mineshaft": "建造一个矿井",
    "Burn something": "烧掉一些东西",
    "Chances": "机会",
    "Copper ore": "铜矿",
    "Defeat the amalgam": "击败汞合金",
    "Defeat the eternal lich": "击败永恒巫妖",
    "Ent Gear": "Ent装备",
    "Fire in the hole": "洞里有火",
    "Forge connector": "锻造连接器",
    "Fuse alloys into something colder": "将合金熔合成更冷的东西",
    "Get 10 levels of vampirism": "获得 10 个吸血鬼等级",
    "Get bartering to level 10": "以物易物达到 10 级",
    "Gold ore": "金矿",
    "Horizon": "地平线",
    "I hope it's a ratio of 1:4": "我希望比例是1:4",
    "Improved tooling": "改良的工具",
    "In the wind": "在风中",
    "Increase tree sizes": "增加树木大小",
    "Iron ore": "铁矿石",
    "is currently replaced by": "目前被替换为",
    "Just like a monarchy": "就像君主制一样",
    "Make a plank ruler": "做一把木板尺",
    "Make alloy tools": "制作合金工具",
    "Make an alloy": "制作合金",
    "Normal log": "普通木头",
    "Professionnal swindler": "职业骗子",
    "Pyrite coin": "黄铁矿币",
    "Red fabric": "红色布料",
    "Respec Swaps": "重新指定互换",
    "Rotten flesh": "烂肉",
    "Rusty gear": "生锈的装备",
    "Safety first": "安全第一",
    "Slime core": "史莱姆核心",
    "Slime core shard": "史莱姆核心碎片",
    "Slime goo": "粘液",
    "Smelt an ingot": "熔炼了一个锭",
    "Soaked log": "浸泡过的原木",
    "Start making planks": "开始制作木板",
    "Swap": "交换",
    "The Incomplete Ghost": "不完整的幽灵",
    "Tin ore": "锡矿石",
    "tokens": "代币",
    "Tree connector": "树连接器",
    "Unlock the Casino": "解锁赌场",
    "Weights": "重量",
    "Wooden Gear": "木制装备",
    "You are past endgame. Content may not be balanced.": "你已经过了残局了。 内容可能不平衡。",
    "You have 5.00% to get a token every item drop roll": "您有 5.00% 的机会在每次掉落物品时获得一个代币",
    "Amount": "数量",
    "Bartering Station": "易货站",
    "Birch": "桦木",
    "Chance to cut an additionnal piece of wood: 18.50%": "额外砍伐一块木头的几率：18.50%",
    "Convert 1% of your logs into planks": "将 1% 的原木转化为木板",
    "Convert wood": "转换木材",
    "Crafting now consumes 90% of costs": "制作现在消耗 90% 的成本",
    "Crafting Table": "工艺台",
    "Double tree growth speed": "树木生长速度翻倍",
    "Double tree health,": "双倍树生命值，",
    "Driftwood": "浮木",
    "Driftwood Destroyer": "浮木毁灭者",
    "Forest": "森林",
    "Increases damage by driftwood health when chopping driftwood": "砍伐浮木时增加浮木健康造成的伤害",
    "Mechanical Sawmill": "机械锯木厂",
    "Mineshaft": "矿井",
    "Mining deep": "采矿深度",
    "Oak": "橡木",
    "Or by 10% of it when not": "或在不使用时减少 10%",
    "Passively cut the current tree with 25% of your damage": "以 25% 的伤害被动砍倒当前的树",
    "Planks increase mined amount": "木板增加开采量",
    "Red brown": "棕红色",
    "Red brown  amalgam": "红棕色汞齐",
    "Saw": "锯子",
    "Size": "大小",
    "Soaked Axe": "浸湿的斧头",
    "Soaked Logs boost damage": "浸泡过的原木会增加伤害",
    "Tree": "树",
    "Unlock a new skill to earn more coins": "解锁新技能以赚取更多金币",
    "Wet Weapon": "湿武器",
    "Wood Chips": "木屑",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Gray  slime": "灰色史莱姆",
    "Red  slime": "红色史莱姆",
    "Black  slime": "黑色史莱姆",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13，Coin: 14，Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Color Levels: ": "彩色等级：",
    "Current damage: ": "当前伤害：",
    "Disable Luck: ": "禁用运气：",
    "Slime: ": "史莱姆: ",
    "Goblin: ": "哥布林: ",
    "Ent: ": "Ent: ",
    "Zombie: ": "僵尸: ",
    "Slime dropped nothing": "史莱姆什么也没掉落",
    "Fractional Chance Mode: ": "分数几率模式：",
    "Damage *": "伤害 *",
    "Global chance multiplier: ": "全局几率乘数：",
    "Chance to mine something: ": "有几率开采一些东西：",
    "Mined nothing": "什么也没开采到",
    "Slime level *": "史莱姆等级 *",
    "Time speed: *": "时间速度: *",
    "cost *": "成本 *",
    "Experience gain *": "经验增益 *",
    "Value: ": "价值: ",
    "cost /": "成本 /",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin，14 Coin，15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) \/ ([\d\.,]+) \(\+([\d\.]+)\/s\)$/,
    /^\/([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(\+([\d\.]+)\/s\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\-([\d\.]+) \/ ([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) dps$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\*([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\*([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\*([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Your next swap will cost (.+) tokens$/, '你下一次交换会花费 $1 代币'],
    [/^You have swapped (.+) times$/, '你交换了 $1 次'],
    [/^Cut (.+) normal log and (.+) normal log$/, '砍伐 $1 普通原木 和 $2 普通原木'],
    [/^Cut (.+) soaked log and (.+) soaked log$/, '砍伐 $1 浸泡过的原木 和 $2 浸泡过的原木'],
    [/^Amalgam dropped (.+) slime goo, (.+) slime core shard, (.+) slime core, (.+) red fabric, (.+) pyrite coin, (.+) rusty gear, (.+) rotten flesh, (.+) iron ore, (.+) brain, (.+) leaf, (.+) normal log, and (.+) seed$/, '汞合金掉落 $1 史莱姆粘液，$2 史莱姆核心碎片，$3 史莱姆核心，$4 红色布料，$5 黄铁矿币，$6 生锈的装备，$7 腐肉，$8 铁矿石，$9 大脑，$10 树叶，$11 普通原木和 $12 种子'],
    [/^Amalgam dropped (.+) slime goo, (.+) slime core shard, (.+) slime core, (.+) red fabric, (.+) pyrite coin, (.+) rusty gear, (.+) rotten flesh, (.+) iron ore, (.+) brain, (.+) leaf, (.+) normal log, and (.+) seed \((.+) times\)$/, '汞合金掉落 $1 史莱姆粘液，$2 史莱姆核心碎片，$3 史莱姆核心，$4 红色布料，$5 黄铁矿币，$6 生锈的装备，$7 腐肉，$8 铁矿石，$9 大脑，$10 树叶，$11 普通原木和 $12 种子（$13 次）'],
    [/^Amalgam dropped (.+) slime goo, (.+) slime core shard, (.+) slime core, (.+) red fabric, (.+) pyrite coin, (.+) rusty gear, (.+) rotten flesh, (.+) iron ore, (.+) brain, (.+) leaf, and (.+) normal log$/, '汞合金掉落 $1 史莱姆粘液，$2 史莱姆核心碎片，$3 史莱姆核心，$4 红色布料，$5 黄铁矿币，$6 生锈的装备，$7 腐肉，$8 铁矿石，$9 大脑，$10 树叶，以及 $11 普通原木'],
    [/^Amalgam dropped (.+) slime goo, (.+) slime core shard, (.+) slime core, (.+) red fabric, (.+) pyrite coin, (.+) rusty gear, (.+) rotten flesh, (.+) iron ore, (.+) leaf, and (.+) normal log$/, '汞合金掉落 $1 史莱姆粘液，$2 史莱姆核心碎片，$3 史莱姆核心，$4 红色布料，$5 黄铁矿币，$6 生锈的装备，$7 腐肉，$8 铁矿石，$9 树叶，以及 $10 普通原木'],
    [/^Amalgam dropped (.+) slime goo, (.+) slime core shard, (.+) slime core, (.+) red fabric, (.+) pyrite coin, (.+) rusty gear, (.+) rotten flesh, (.+) iron ore, (.+) brain, (.+) leaf, and (.+) normal log \((.+) times\)$/, '汞合金掉落 $1 史莱姆粘液，$2 史莱姆核心碎片，$3 史莱姆核心，$4 红色布料，$5 黄铁矿币，$6 生锈的装备，$7 腐肉，$8 铁矿石，$9 大脑，$10 树叶，以及 $11 普通原木（$12 次）'],
    [/^Mining \*(.+) ore$/, '开采 \*$1 矿石'],
    [/^Mined (.+) copper ore, (.+) tin ore, (.+) coal, (.+) iron ore, (.+) gold ore, and (.+) stone$/, '开采铜矿石 $1 铁矿石，$2 锡矿石，$3 煤， $4 铁矿石，$5 金矿石 ，$6 石头'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) effective investments$/, '你有 $1 有效投资'],
    [/^You have (.+) effective repaid loans$/, '您有 $1 有效已偿还贷款'],
    [/^Next at (.+) total value$/, '下一个在 $1 总价值'],
    [/^Your items have (.+) total value$/, '您的物品总价值 $1'],
    [/^Passively deal (.+) of your damage every second$/, '每秒造成 $1 的被动伤害'],
    [/^Your (.+) coal braziers                    give (.+) effective levels to$/, '你的 $1 煤火盆给予 $2 有效等级到'],
    [/^Your (.+) gold piles                    represent (.+) gold for$/, '你的 $1 金堆代表 $2 金币对于'],
    [/^Your (.+) iron chests                    give (.+) effective levels to$/, '你的 $1 铁箱给予 $2 有效等级到'],
    [/^Your (.+) knowledge balls                    add (.+) skill points$/, '你的 $1 知识球增加 $2 技能点'],
    [/^Your (.+) rotten bags                    multiply drop chances by (.+)$/, '你的 $1 烂袋子 掉落几率乘以 $2'],
    [/^Your (.+) red slimes                    multiply damage by (.+)$/, '你的 $1 红色史莱姆 伤害乘以 $2'],
    [/^Your (.+) coin bags                    multiply drop chances by (.+) and multiply coins gain by (.+)$/, '你的 $1 硬币袋 掉落几率乘以 $2 并 乘以金币增益 $3'],
    [/^Your (.+) coin bags                    multiply drop chances by (.+)$/, '你的 $1 硬币袋 掉落几率乘以 $2'],
    [/^Your (.+) gear golems                    multiply skill speed by (.+)$/, '你的 $1 装备傀儡 将技能速度乘以 $2'],
    [/^Your (.+) iron battle axes                    multiply enemy damage by (.+)$/, '你的 $1 铁战斧 乘以敌人伤害 $2'],
    [/^Your (.+) copper golems                    multiply mining chance by (.+)$/, '你的 $1 铜傀儡 将采矿几率乘以 $2'],
    [/^Your (.+) crude bronze gears                    increase time speed by (.+)$/, '你的 $1 粗制青铜装备 提高时间速度 $2'],
    [/^Your (.+) goblin gears                    increase time speed by (.+)$/, '你的 $1 哥布林装备 提高时间速度 $2'],
    [/^Your (.+) gold gears                    increase time speed by (.+)$/, '你的 $1 黄金装备 提高时间速度 $2'],
    [/^Your (.+) stone gears                    increase time speed by (.+)$/, '你的 $1 石头装备 提高时间速度 $2'],
    [/^Your (.+) zombie gears                    increase time speed by (.+)$/, '你的 $1 僵尸装备 提高时间速度 $2'],
    [/^Your (.+) wooden gears                    increase time speed by (.+)$/, '你的 $1 木制装备 提高时间速度 $2'],
    [/^Your (.+) ent gears                    increase time speed by (.+)$/, '你的 $1 ent装备 提高时间速度 $2'],
    [/^Your (.+) iron gears                    increase time speed by (.+)$/, '你的 $1 铁装备 提高时间速度 $2'],
    [/^Your (.+) money gears                    increase time speed by (.+)$/, '你的 $1 金钱装备 提高时间速度 $2'],
    [/^Your (.+) slime gears                    increase time speed by (.+)$/, '你的 $1 史莱姆装备 提高时间速度 $2'],
    [/^Your (.+) tin chests                    multiply drop and mining chance by (.+) and keep (.+) mining upgrades through resets$/, '你的 $1 锡箱将掉落和采矿机会乘以 $2，并通过重置保留 $3 采矿升级'],
    [/^Your (.+) stone furnace                    multiply ore health by (.+)$/, '你的 $1 个石炉将矿石生命值乘以 $2'],
    [/^You have (.+) bonus achievements$/, '你有 $1 奖励成就'],
    [/^You have (.+) secret achievements$/, '你有 $1 秘密成就'],
    [/^You have (.+) achievements$/, '你有 $1 成就'],
    [/^Your (.+) storage slimes                    hold (.+) experience upgrades                    and multiply drop chances by (.+)$/, '你的 $1 个储存史莱姆拥有 $2 经验升级并将掉落几率乘以 $3'],
    [/^Your (.+) sticky traps                    divide enemy health by (.+)$/, '你的 $1 个粘性陷阱将敌人的生命值除以 $2'],
    [/^Your (.+) books of slimes                    multiply experience gain by (.+) \((.+) for slimes\)$/, '你的 $1 本史莱姆之书将经验值乘以 $2（史莱姆为 $3）'],
    [/^Reach (.+) experience points to unlock \(You have (.+) experience points\)$/, '达到 $1 经验值即可解锁（您有 $2 经验值）'],
    [/^(.+) \/ (.+) bouns achievements$/, '$1 \/ $2 奖励成就'],
    [/^(.+) \/ (.+) achievements$/, '$1 \/ $2 成就'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) \/s$/, '$1 \/秒'],
    [/^([\d\.]+) heat$/, '$1 热量'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) points assigned to learning$/, '$1 点数分配到学习'],
    [/^level \*([\d\.]+), chance \*([\d\.]+)$/, '等级 \*$1, 几率 \*$2'],
    [/^([\d\.]+) points assigned to attacking$/, '$1 点数分配到 攻击'],
    [/^\+([\d\.]+) health, \*([\d\.]+) xp$/, '\+$1 生命值, \*$2 经验值'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) items$/, '$1e$2 物品'],
    [/^([\d\.]+)e([\d\.,]+) tokens$/, '$1e$2 代币'],
    [/^([\d\.]+)e([\d\.,]+) heat$/, '$1e$2 热量'],
    [/^([\d\.,]+) experience$/, '$1 经验值'],
    [/^Kill ([\d\.,]+) slimes$/, '杀死 $1 史莱姆'],
    [/^([\d\.,]+) heat$/, '$1 热量'],
    [/^([\d\.,]+) kills$/, '$1 击杀'],
    [/^([\d\.,]+) items$/, '$1 物品'],
    [/^([\d\.,]+) levels$/, '$1 级'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) secrets$/, '$1 秘密'],
    [/^([\d\.,]+) bosses$/, '$1 Boss'],
    [/^([\d\.,]+) tokens$/, '$1 代币'],
    [/^([\d\.,]+) stone$/, '$1 石头'],
    [/^([\d\.,]+) tin ore$/, '$1 锡矿石'],
    [/^([\d\.,]+) copper ore$/, '$1 铜矿石'],
    [/^Attacking level ([\d\.,]+)$/, '攻击等级 $1'],
    [/^Slime dropped ([\d\.,]+) slime core$/, '史莱姆掉落了 $1 史莱姆核心'],
    [/^Slime dropped ([\d\.,]+) slime goo$/, '史莱姆掉落了 $1 史莱姆粘液'],
    [/^Slime dropped ([\d\.,]+) slime goo and ([\d\.,]+) slime core$/, '史莱姆掉落了 $1 史莱姆粘液 和 $2 史莱姆核心'],
    [/^Slime dropped ([\d\.,]+) slime goo and ([\d\.,]+) slime core shard$/, '史莱姆掉落了 $1 史莱姆粘液 和 $2 史莱姆核心碎片'],
    [/^Slime dropped ([\d\.,]+) slime goo and ([\d\.,]+) slime core shard \(([\d\.,]+) times\)$/, '史莱姆掉落了 $1 史莱姆粘液 和 $2 史莱姆核心碎片 \($3 times\)'],
    [/^Slime dropped ([\d\.,]+) slime goo \(([\d\.,]+) times\)$/, '史莱姆掉落了 $1 史莱姆粘液（$2 次）'],
    [/^Slime dropped ([\d\.,]+) slime core shard$/, '史莱姆掉落了 $1 史莱姆核心碎片'],
    [/^ \(([\d\.,]+) times\)$/, '（$1 次）'],
    [/^Learning level ([\d\.,]+)$/, '学习等级 $1'],
    [/^Level ([\d\.,]+) slime$/, '$1 级史莱姆'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Mined ([\d\.]+) tin ore$/, '开采了 $1 锡矿石'],
    [/^Mined ([\d\.]+) stone \(([\d\.,]+) times\)$/, '开采了 $1 石头（$2 次）'],
    [/^Mined ([\d\.]+) tin ore \(([\d\.,]+) times\)$/, '开采了 $1 锡矿石（$2 次）'],
    [/^Mined ([\d\.]+) copper ore \(([\d\.,]+) times\)$/, '开采了 $1 铜矿石（$2 次）'],
    [/^Mined ([\d\.]+) copper ore$/, '开采了 $1 铜矿石'],
    [/^Mined ([\d\.]+) copper ore and (.+) stone$/, '开采了 $1 铜矿石 和 $2 石头'],
    [/^Mined ([\d\.]+) copper ore and (.+) stone \(([\d\.,]+) times\)$/, '开采了 $1 铜矿石 和 $2 石头（$3 次）'],
    [/^Mined ([\d\.]+) tin ore and (.+) stone$/, '开采了 $1 锡矿石 和 $2 石头'],
    [/^Mined ([\d\.]+) tin ore and (.+) stone \(([\d\.,]+) times\)$/, '开采了 $1 锡矿石 和 $2 石头（$3 次）'],
    [/^Mined ([\d\.]+) stone$/, '开采了 $1 石头'],
    [/^Mined ([\d\.]+) copper ore, (.+) tin ore, and (.+) stone$/, '开采了 $1 铜矿石，$2 锡矿石，以及 $3 石头'],
    [/^Base time speed: (.+) seconds\/s$/, '基本时间速度：$1秒\/秒'],
    [/^Cost: (.+) experience$/, '成本：$1 经验值'],
    [/^Cost: (.+) kills$/, '成本：$1 击杀'],
    [/^Cost: (.+) red fabric and (.+) pyrite coin$/, '成本：$1 红色布料和 $2 黄铁矿币'],
    [/^Cost: (.+) red fabric and (.+) slime goo$/, '成本：$1 红色布料和 $2 史莱姆粘液'],
    [/^Cost: (.+) slime goo and (.+) slime core shard$/, '成本：$1 史莱姆粘液和 $2 史莱姆核心碎片'],
    [/^Cost: (.+) slime goo and (.+) slime core$/, '成本：$1 史莱姆粘液和 $2 史莱姆核心'],
    [/^Cost: (.+) slime goo, (.+) slime core shard, and (.+) slime core$/, '成本：$1 史莱姆粘液，$2 史莱姆核心碎片，和 $3 史莱姆核心'],
    [/^Cost: (.+) slime core, (.+) rusty gear, and (.+) brain$/, '成本：$1 史莱姆核心，$2 生锈的装备，以及 $3 大脑'],
    [/^Cost: (.+) stone, (.+) copper ore, and (.+) tin ore$/, '成本：$1 石头，$2 铜矿石，以及 $3 锡矿石'],
    [/^Cost: (.+) copper ore and (.+) tin ore$/, '成本：$1 铜矿石 和 $2 锡矿石'],
    [/^Cost: (.+) copper ore and (.+) slime core$/, '成本：$1 铜矿石 和 $2 史莱姆核心'],
    [/^Cost: (.+) stone and (.+) copper ore$/, '成本：$1 石头 和 $2 铜矿石'],
    [/^Cost: (.+) stone and (.+) coal$/, '成本：$1 石头 和 $2 煤'],
    [/^Cost: (.+) copper ore$/, '成本：$1 铜矿石'],
    [/^Cost: (.+) iron ore$/, '成本：$1 铁矿石'],
    [/^Cost: (.+) gold ore$/, '成本：$1 金矿石'],
    [/^Cost: (.+) iron ore, (.+) copper ore, and (.+) tin ore$/, '成本：$1 铁矿石，$2 铜矿石，以及 $3 锡矿石'],
    [/^Cost: (.+) tin ore$/, '成本：$1 锡矿石'],
    [/^Cost: (.+) tin ore, (.+) copper ore, and (.+) slime goo$/, '成本：$1 锡矿石，$2 铜矿石，以及 $3 史莱姆粘液'],
    [/^Cost: (.+) copper ore and (.+) stone$/, '成本：$1 铜矿石 和 $2 石头'],
    [/^Cost: (.+) copper ore, (.+) tin ore, and (.+) stone$/, '成本：$1 铜矿石，$2 锡矿石，以及 $3 石头'],
    [/^Cost: (.+) copper ore, (.+) tin ore, and (.+) rusty gear$/, '成本：$1 铜矿石，$2 锡矿石，以及 $3 生锈的装备'],
    [/^Cost: (.+) red fabric, (.+) pyrite coin, and (.+) rusty gear$/, '成本：$1 红布，$2 黄铁矿币，以及 $3 生锈的装备'],
    [/^Cost: (.+) slime goo, (.+) copper ore, and (.+) rusty gear$/, '成本：$1 史莱姆粘液，$2 铜矿石，以及 $3 生锈的装备'],
    [/^Cost: (.+) rusty gear$/, '成本：$1 生锈的装备'],
    [/^Cost: (.+) tin ore and (.+) stone$/, '成本：$1 锡矿石 和 $2 石头'],
    [/^Cost: (.+) iron ore and (.+) slime goo$/, '成本：$1 铁矿石 和 $2 史莱姆粘液'],
    [/^Cost: (.+) slime goo$/, '成本：$1 史莱姆粘液'],
    [/^Cost: (.+) rotten flesh, (.+) iron ore, and (.+) brain$/, '成本：$1 腐肉，$2 铁矿石，和 $3 大脑'],
    [/^Cost: (.+) rotten flesh and (.+) red fabric$/, '成本：$1 腐肉和 $2 红色布料'],
    [/^Cost: (.+) bronze ingot and (.+) steel ingot$/, '成本：$1 青铜锭 和 $2 钢锭'],
    [/^Cost: (.+) copper ingot and (.+) tin ingot$/, '成本：$1 铜锭 和 $2 锡锭'],
    [/^Cost: (.+) copper ingot$/, '成本：$1 铜锭'],
    [/^Cost: (.+) tin ingot$/, '成本：$1 锡锭'],
    [/^Cost: (.+) gold ingot$/, '成本：$1 金锭'],
    [/^Cost: (.+) rotten flesh, (.+) brain, and (.+) iron ingot$/, '成本：$1 腐肉，$2 大脑，以及 $3 铁锭'],
    [/^Cost: (.+) iron ingot$/, '成本：$1 铁锭'],
    [/^Cost: (.+) stone brick$/, '成本：$1 石砖'],
    [/^Cost: (.+) coal$/, '成本：$1 煤'],
    [/^Cost: (.+) leaf, (.+) normal log, and (.+) seed$/, '成本：$1 树叶，$2 普通木头，以及 $3 种子'],
    [/^Cost: (.+) soaked log, (.+) normal log, and (.+) plank$/, '成本：$1 浸泡过的木头，$2 普通木头，以及 $3 木板'],
    [/^Cost: (.+) plank$/, '成本：$1 木板'],
    [/^Cost: (.+) normal log$/, '成本：$1 普通原木'],
    [/^Cost: (.+) soaked log$/, '成本：$1 潮湿的原木'],
    [/^Cost: ([\d\.]+) stone$/, '成本：$1 石头'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Mining: (.+) \(in group\)$/, '采矿：$1（成群）'],
    [/^Shallow mining: (.+) \(in group\)$/, '浅层采矿：$1（成群）'],
    [/^Requires: (.+) levels$/, '要求：$1 级'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) experience points$/, '要求：$1 经验点数'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);